# Generated by Django 4.0.1 on 2022-02-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorialResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('arg1', models.IntegerField()),
                ('result', models.TextField(blank=True)),
                ('ret_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FibonacciResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('arg1', models.IntegerField()),
                ('result', models.TextField(blank=True)),
                ('ret_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('arg1', models.FloatField()),
                ('arg2', models.FloatField()),
                ('result', models.TextField(blank=True)),
                ('ret_code', models.IntegerField()),
            ],
        ),
    ]
